name: deploy-posts

on:
  push:
    branches:
      - main
    paths:
      - 'posts/**'
      - 'common/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd posts && docker build -t justinnicky/posts .
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push justinnicky/posts
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - run: doctl kubernetes cluster kubeconfig save 39945a1d-8350-4d99-adf2-fd75c452831f
      - run: kubectl rollout restart deployment posts-depl
