name: deploy-manifests

on:
  push:
    branches:
      - main
    paths:
      - "infra/**"


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - run: doctl kubernetes cluster kubeconfig save 39945a1d-8350-4d99-adf2-fd75c452831f
      - run: kubectl apply -f infra/k8s && kubectl apply -f infra/k8s-prod
