name: deploy-chats

on:
  push:
    branches:
      - main
    paths:
      - 'chats/**'
      - 'common/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd chats && docker build -t justinnicky/chats .
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push justinnicky/chats
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - run: doctl kubernetes cluster kubeconfig save 39945a1d-8350-4d99-adf2-fd75c452831f
      - run: kubectl rollout restart deployment chats-depl
